<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('ramp_transactions', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            $table->string('type')->index(); // 'on_ramp' (buy crypto), 'off_ramp' (sell crypto)
            $table->string('merchant_reference')->unique(); // Unique identifier generated by us e.g. ONRAMP_82_123456
            $table->string('public_id')->nullable(); // Quidax generated public_id
            $table->string('reference')->nullable(); // Quidax generated reference e.g. TRX-WAXR...
            
            $table->string('from_currency');
            $table->string('to_currency');
            
            $table->decimal('from_amount', 16, 8); // Handles large NGN or small crypto amounts
            $table->decimal('to_amount', 16, 8)->nullable();
            
            $table->string('network')->nullable(); // crypto network e.g. bep20
            $table->string('wallet_address')->nullable(); // For on-ramp to receive crypto
            
            // Off-Ramp / On-Ramp bank payout info
            $table->string('bank_name')->nullable();
            $table->string('bank_code')->nullable();
            $table->string('account_name')->nullable();
            $table->string('account_number')->nullable();
            
            $table->string('status')->default('pending'); // pending, confirmed, processing, completed, failed
            
            $table->decimal('blockchain_fee', 16, 8)->nullable();
            $table->decimal('processor_fee', 16, 8)->nullable();
            $table->decimal('stamp_charge', 16, 8)->nullable();
            $table->decimal('vat', 16, 8)->nullable();
            
            $table->string('transfer_session_id')->nullable(); // SafeHaven Name Enquiry Session ID or similar idempotency key
            
            $table->json('metadata')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('ramp_transactions');
    }
};
